version: "3.8"

services:
  fastapi_app:
    build: .
    container_name: fastapi_app
    restart: always
    depends_on:
      - postgres_db
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - fastapi_network

  postgres_db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: fastapi_user
      POSTGRES_PASSWORD: fastapi_password
      POSTGRES_DB: fastapi_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - fastapi_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - fastapi_network

volumes:
  postgres_data:

networks:
  fastapi_network:
